version: '3.8'

services:
  webapp:
    container_name: dapper-identity-webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # -  ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=db;Initial Catalog=DapperIdentity;User Id=sa;Password=Israt@007@Jahan;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: dapper-identity-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Israt@007@Jahan
      - MSSQL_PID=Express
    ports:
      - "11433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI


volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge