version: '3.8'

services:
  webapp:
    container_name: dapper-identity-webapp
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8080:8080
      # - 8081:8081
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      -  ASPNETCORE_HTTP_PORTS=8080
      # -  ASPNETCORE_HTTPS_PORTS=8081
      -  ConnectionStrings__DefaultConnection=Server=db;Database=DapperIdentity;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - app-network
  db:
    container_name: dapper-identity-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL-PID=Express
    ports:
      - "11433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network

volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge